name: Node JS CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_nodejs_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: echo "Building application" # not working because no provision for build script in package.json, simply echo it.

      - name: Run ESlint
        run: echo "Running ESlint"

      - name: Run Unit Tests
        run: echo "Running Unit Tests"
        